CarfulMetaData/main/default/objects/Accessory__c/Accessory__c.object-meta.xml
<CustomObject>
    <description>Products or additions that come with a new car.</description>
    <label>Accessory</label>
    <nameField>
        <label>Accessory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CarfulMetaData/main/default/objects/Accessory__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price for accessory</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

CarfulMetaData/main/default/objects/Accessory_Catalogue_Entry__c/Accessory_Catalogue_Entry__c.object-meta.xml
<CustomObject>
    <description>Junction object  that denotes an entry of an accessory to a connected vehicle make/model.</description>
    <label>Accessory Catalogue Entry</label>
    <nameField>
        <label>Accessory Connect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessory Catalogue Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CarfulMetaData/main/default/objects/Accessory_Catalogue_Entry__c/fields/Accessory__c.field-meta.xml
<CustomField>
    <fullName>Accessory__c</fullName>
    <description>The accessory this accessory catalogue entry describes.
This accessory can be included with the product make/model specified in the product lookup field.</description>
    <label>Accessory</label>
    <referenceTo>Accessory__c</referenceTo>
    <relationshipLabel>Accessory Catalogue Entries</relationshipLabel>
    <relationshipName>Accessory_Catalogue_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CarfulMetaData/main/default/objects/Accessory_Catalogue_Entry__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product this entry is applied to.
The connected accessory denotes a possible accessory that can be included with this product make/model.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Accessory Catalogue Entries</relationshipLabel>
    <relationshipName>Accessory_Catalogue_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

CarfulMetaData/main/default/objects/Customization__c/Customization__c.object-meta.xml
<CustomObject>
    <description>A built in customized feature to be applied to a vehicle.</description>
    <label>Customization</label>
    <nameField>
        <label>Customization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CarfulMetaData/main/default/objects/Customization_Catalogue_Entry__c/Customization_Catalogue_Entry__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect customizations and the vehicles they can be applied to.</description>
    <label>Customization Catalogue Entry</label>
    <nameField>
        <label>Customization Catalogue Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customization Catalogue Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CarfulMetaData/main/default/objects/Customization_Catalogue_Entry__c/fields/Customization__c.field-meta.xml
<CustomField>
    <fullName>Customization__c</fullName>
    <description>The customization this customization application refers to.</description>
    <label>Customization</label>
    <referenceTo>Customization__c</referenceTo>
    <relationshipLabel>Customization Catalogue Entries</relationshipLabel>
    <relationshipName>Customization_Catalogue_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CarfulMetaData/main/default/objects/Customization_Catalogue_Entry__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The vehicle this customization application is applied to.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Customization Catalogue Entries</relationshipLabel>
    <relationshipName>Customization_Catalogue_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

CarfulMetaData/main/default/objects/Product2/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VBcontainerController.cls
public with sharing class VBcontainerController {
    @AuraEnabled
    public static getMake(){
    List<Product2> myList = [SELECT Name, Price__c, Make__c, Model__c, Year__c,
    (SELECT Name, Customization__r.Price__c, Customization__r.Name, Customization__r.Id FROM Customization_Catalogue_Entries__r),
    (SELECT Name, Color__r.Price__c, Color__r.Name, Color__r.Id FROM Color_Catalogue_Entries__r),
    (SELECT Name, Accessory__r.Price__c, Accessory__r.Name, Accessory__r.Id FROM Accessory_Catalogue_Entries__r)
    FROM Product2]; 
 
    //make root of tree
    Map<String, Map<String, Map<String, Map<String, Map<String, Map<String, String>>>>>> returnMap = new Map<String, Map<String, Map<String, Map<String, Map<String, Map<String, String>>>>>>();
 
    //make tree
    for (Product2 curProduct : myList) {
        //make root of tree
        if (returnMap.get(curProduct.Make__c))  {
            returnMap.put(curProduct.Make__c, new Map<String, Map<String, Map<String, Map<String, Map<String, String>>>>>());
        }
        
        if (returnMap.get(curProduct.Model__c)) {
            returnMap.get(curProduct.Make__c).put(curProduct.Model__c, new Map<String, Map<String, Map<String, Map<String, String>>>>());
        }
 
        Map<String, Map<String, String>> custInfo = new Map<String, Map<String, String>>();
        
        for (Customization_Catalogue_Entry__c cCatEntry : curProduct.Customization_Catalogue_Entries__r) {
            custInfo.put(cCatEntry.Customization__r.Name, new Map<String, String>());
 
            custInfo.get(cCatEntry.Customization__r.Name).put('Price', cCatEntry.Customization__r.Price__c);
            custInfo.get(cCatEntry.Customization__r.Name).put('Name', cCatEntry.Customization__r.Name);
            custInfo.get(cCatEntry.Customization__r.Name).put('Id', cCatEntry.Customization__r.Id);
            custInfo.get(cCatEntry.Customization__r.Name).put('ImgUrl', '');
        }
 
        Map<String, Map<String, String>> colorInfo = new Map<String, Map<String, String>>();
        
        for (Color_Catalogue_Entry__c colorCatEntry : curProduct.Color_Catalogue_Entries__r) {
            colorInfo.put(colorCatEntry.Color__r.Name, new Map<String, String>());
 
            colorInfo.get(colorCatEntry.Color__r.Name).put('Price', colorCatEntry.Color__r.Price__c);
            colorInfo.get(colorCatEntry.Color__r.Name).put('Name', colorCatEntry.Color__r.Name);
            colorInfo.get(colorCatEntry.Color__r.Name).put('Id', colorCatEntry.Color__r.Id);
            colorInfo.get(colorCatEntry.Color__r.Name).put('ImgUrl', '');
        }
 
        Map<String, Map<String, String>> accInfo = new Map<String, Map<String, String>>();
        
        for (Accessory_Catalogue_Entry__c accCatEntry : curProduct.Accessory_Catalogue_Entries__r) {
            accInfo.put(accCatEntry.Accessory__r.Name, new Map<String, String>());
 
            accInfo.get(accCatEntry.Accessory__r.Name).put('Price', accCatEntry.Accessory__r.Price__c);
            accInfo.get(accCatEntry.Accessory__r.Name).put('Name', accCatEntry.Accessory__r.Name);
            accInfo.get(accCatEntry.Accessory__r.Name).put('Id', accCatEntry.Accessory__r.Id);
            accInfo.get(accCatEntry.Accessory__r.Name).put('ImgUrl', '');
        }
 
        Map<String, Map<String, Map<String, String>>> yearInfo = new Map<String, Map<String, Map<String, String>>>();
        yearInfo.put('Accessories', accInfo);
        yearInfo.put('Colors', colorInfo);
        yearInfo.put('Customizations', custInfo);
 
        returnMap.get(curProduct.Make__c).get(curProduct.Model__c).put(curProduct.Year__c, yearInfo);
    }
 
 return returnMap;
    }
 }