CarfulMetaData/main/default/objects/Accessory__c/Accessory__c.object-meta.xml
<CustomObject>
    <description>Products or additions that come with a new car.</description>
    <label>Accessory</label>
    <nameField>
        <label>Accessory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CarfulMetaData/main/default/objects/Accessory_Catalogue_Entry__c/Accessory_Catalogue_Entry__c.object-meta.xml
<CustomObject>
    <description>Junction object  that denotes an entry of an accessory to a connected vehicle make/model.</description>
    <label>Accessory Catalogue Entry</label>
    <nameField>
        <label>Accessory Connect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessory Catalogue Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CarfulMetaData/main/default/objects/Accessory_Catalogue_Entry__c/fields/Accessory__c.field-meta.xml
<CustomField>
    <fullName>Accessory__c</fullName>
    <description>The accessory this accessory catalogue entry describes.
This accessory can be included with the product make/model specified in the product lookup field.</description>
    <label>Accessory</label>
    <referenceTo>Accessory__c</referenceTo>
    <relationshipLabel>Accessory Catalogue Entries</relationshipLabel>
    <relationshipName>Accessory_Catalogue_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CarfulMetaData/main/default/objects/Accessory_Catalogue_Entry__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product this entry is applied to.
The connected accessory denotes a possible accessory that can be included with this product make/model.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Accessory Catalogue Entries</relationshipLabel>
    <relationshipName>Accessory_Catalogue_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

CarfulMetaData/main/default/objects/Customization__c/Customization__c.object-meta.xml
<CustomObject>
    <description>A built in customized feature to be applied to a vehicle.</description>
    <label>Customization</label>
    <nameField>
        <label>Customization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CarfulMetaData/main/default/objects/Customization_Catalogue_Entry__c/Customization_Catalogue_Entry__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect customizations and the vehicles they can be applied to.</description>
    <label>Customization Catalogue Entry</label>
    <nameField>
        <label>Customization Catalogue Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customization Catalogue Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CarfulMetaData/main/default/objects/Customization_Catalogue_Entry__c/fields/Customization__c.field-meta.xml
<CustomField>
    <fullName>Customization__c</fullName>
    <description>The customization this customization application refers to.</description>
    <label>Customization</label>
    <referenceTo>Customization__c</referenceTo>
    <relationshipLabel>Customization Catalogue Entries</relationshipLabel>
    <relationshipName>Customization_Catalogue_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CarfulMetaData/main/default/objects/Customization_Catalogue_Entry__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The vehicle this customization application is applied to.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Customization Catalogue Entries</relationshipLabel>
    <relationshipName>Customization_Catalogue_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

CarfulMetaData/main/default/objects/Paint_Color_Catalogue_Entry__c/Paint_Color_Catalogue_Entry__c.object-meta.xml
<CustomObject>
    <description>Object representing all the possible paint colors for a specific product</description>
    <label>Paint Color Catalogue Entry</label>
    <nameField>
        <label>Paint Color Catalogue Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paint Color Catalogue Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CarfulMetaData/main/default/objects/Paint_Color_Catalogue_Entry__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the product this paint color catalogue entry applies to</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Paint Color Catalogue Entries</relationshipLabel>
    <relationshipName>Paint_Color_Catalogue_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

CarfulMetaData/main/default/objects/Product2/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Make</valueSetName>
    </valueSet>
</CustomField>

CarfulMetaData/main/default/objects/Product2/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vehicle_Make__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Model</valueSetName>
    </valueSet>
</CustomField>

CarfulMetaData/main/default/objects/Product2/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

CarfulMetaData/main/default/globalValueSets/Vehicle_Make.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Subaru</fullName>
    </customValue>
    <customValue>
        <fullName>Toyota</fullName>
    </customValue>
    <masterLabel>Vehicle Make</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CarfulMetaData/main/default/globalValueSets/Vehicle_Model.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>4Runner</fullName>
    </customValue>
    <customValue>
        <fullName>Accord</fullName>
    </customValue>
    <customValue>
        <fullName>Civic</fullName>
    </customValue>
    <customValue>
        <fullName>Durango</fullName>
    </customValue>
    <customValue>
        <fullName>F-150</fullName>
    </customValue>
    <customValue>
        <fullName>Focus</fullName>
    </customValue>
    <customValue>
        <fullName>Impreza</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Ram</fullName>
    </customValue>
    <customValue>
        <fullName>Tacoma</fullName>
    </customValue>
    <customValue>
        <fullName>Tundra</fullName>
    </customValue>
    <customValue>
        <fullName>WRX</fullName>
    </customValue>
    <masterLabel>Vehicle Model</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/MyVehicleListController.cls
public with sharing class MyVehicleListController {
   //Nested Soql query to get data from product2
   @AuraEnabled
   public static List<Product2> getMake(Id recordId){
       List<Product2> makelist = [SELECT Vehicle_Make__c, Vehicle_Model__c, Year__c, 
       (SELECT ID, Name FROM Customization_Catalogue_Entries__r), 
       (SELECT ID, Name FROM Paint_Color_Catalogue_Entries__r), 
       (SELECT ID, Name FROM Accessory_Catalogue_Entries__r) FROM Product2 WHERE Id = :recordId];
       return makelist;   
   }
   //child to parent query
   @AuraEnabled
   public static List<Product2> getData(){
   List<Product2> myList = [SELECT Name, Price__c, Make__c, Model__c, Year__c,
        (SELECT Name, Customization__r.Price__c, Customization__r.Name, Customization__r.Id FROM Customization_Catalogue_Entries__r),
        (SELECT Name, Color__r.Price__c, Color__r.Name, Color__r.Id FROM Color_Catalogue_Entries__r),
        (SELECT Name, Accessory__r.Price__c, Accessory__r.Name, Accessory__r.Id FROM Accessory_Catalogue_Entries__r)
        FROM Product2];
         return myList;
}

}
       