CarfulMetaData/main/default/objects/AssociatedBrand__c/AssociatedBrand__c.object-meta.xml
<CustomObject>
    <description>Object containing all associated brands of carful.</description>
    <label>Associated Brand</label>
    <nameField>
        <label>AssociatedBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CarfulMetaData/main/default/objects/AssociatedBrand__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <description>The make this brand sells.</description>
    <label>Make</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Make</valueSetName>
    </valueSet>
</CustomField>

CarfulMetaData/main/default/objects/AssociatedBrand__c/fields/Manufacture_Email__c.field-meta.xml
<CustomField>
    <fullName>Manufacture_Email__c</fullName>
    <description>Email to send notifications on incoming orders for manufacturing.</description>
    <externalId>true</externalId>
    <label>Manufacture Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

CarfulMetaData/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <description>A single item in an associated order.</description>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CarfulMetaData/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product(car make/model) this order item contains.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

CarfulMetaData/main/default/objects/Product2/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Make</valueSetName>
    </valueSet>
</CustomField>

CarfulMetaData/main/default/objects/Product2/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vehicle_Make__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Model</valueSetName>
    </valueSet>
</CustomField>

CarfulMetaData/main/default/objects/Product2/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

CarfulMetaData/main/default/globalValueSets/Vehicle_Make.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Subaru</fullName>
    </customValue>
    <customValue>
        <fullName>Toyota</fullName>
    </customValue>
    <masterLabel>Vehicle Make</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CarfulMetaData/main/default/globalValueSets/Vehicle_Model.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>4Runner</fullName>
    </customValue>
    <customValue>
        <fullName>Accord</fullName>
    </customValue>
    <customValue>
        <fullName>Civic</fullName>
    </customValue>
    <customValue>
        <fullName>Durango</fullName>
    </customValue>
    <customValue>
        <fullName>F-150</fullName>
    </customValue>
    <customValue>
        <fullName>Focus</fullName>
    </customValue>
    <customValue>
        <fullName>Impreza</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Ram</fullName>
    </customValue>
    <customValue>
        <fullName>Tacoma</fullName>
    </customValue>
    <customValue>
        <fullName>Tundra</fullName>
    </customValue>
    <customValue>
        <fullName>WRX</fullName>
    </customValue>
    <masterLabel>Vehicle Model</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CarfulNicholas/main/default/classes/orderItemTriggerHandler.cls
public with sharing class orderItemTriggerHandler {
    public static void handleBeforeInsert(List<Order_Item__c> orderList) {
        //create set of Ids of orders inserted
        Set<Id> orderIdSet = new Set<Id>();
        for (Order_Item__c ord : orderList) {
            orderIdSet.add(ord.Id);
        }

        //select all needed information from orders in orderIdSet
        List<Order_Item__c> detailedOrderList = [SELECT Name, Product__r.Vehicle_Make__c, Product__r.Vehicle_Model__c, Product__r.Year__c FROM Order_Item__c WHERE Id IN :orderIdSet];

        //select email and make of all associated brands
        List<AssociatedBrand__c> aBrandList = [SELECT Manufacture_Email__c, Make__c FROM AssociatedBrand__c];

        //create map of make to email body
        Map<String, List<String>> makeToEmailBodyMap = new Map<String, List<String>>();
        
        //instantiate map with keys and empty string list value
        for (AssociatedBrand__c aBrand: aBrandList) {
            makeToEmailBodyMap.put(aBrand.Make__c, new List<String>());
        }

        //for every order item add their info to string list
        
        for (Order_Item__c ordItem : detailedOrderList) {
            makeToEmailBodyMap.get(ordItem.Product__r.Vehicle_Make__c).add(
                '\nOrder Item Id: ' + ordItem.Id +
                '\nMake: ' + ordItem.Product__r.Vehicle_Make__c +
                '\nModel: ' + ordItem.Product__r.Vehicle_Model__c + 
                '\nYear: ' + ordItem.Product__r.Year__c + 
                '\n\n'
            );
        }
        

        //send emails to brands
        for (AssociatedBrand__c aBrand : aBrandList) {
            //skips brand if no cars of the brand are ordered
            if (makeToEmailBodyMap.get(aBrand.Make__c).size() == 0) continue;

            //setup email to be sent
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[]{aBrand.Manufacture_Email__c};
            mail.setToAddresses(toAddresses);
            mail.setReplyTo('support@carful.com');
            mail.setSenderDisplayName('Carful Order Handling Department');
            mail.setSubject('New Order');
            mail.setBccSender(false);
            mail.setUseSignature(false);

            //set email body
            String buildingString = 'Items Ordered: \n\n';
            for (String ordItemString : makeToEmailBodyMap.get(aBrand.Make__c)) {
                buildingString += ordItemString;
            }
            mail.setPlainTextBody(buildingString);

            //send email
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
        }
    }
}